### ISSUE TITLE
Remove the version pinning

### ISSUE THREAD

**Issue by fabaff** [reefab/foobot_async#1]
The version of aiohttp is pinned to [2.3.10](https://github.com/reefab/foobot_async/blob/master/setup.py#L16). Please remove that pinning.

**Comment by Pharizna** [comment]
Thank you ... but how?  To wait until a new HA version? :)

**Comment by fabaff** [comment]
@Pharizna, the `foobot` platform is pulling in `foobot_async` and the version pinning is blocking the installation as Home Assistant requires aiohttp-3.1.x which is already present.

This needs to be fixed here and will require a new release of `foobot_async` which we can use for Home Assistant.

**Comment by reefab** [comment]
This has been fixed. 

The package has been updated with the version 0.3.1 which removes the aiohttp version pinning (and support for python 3.4).

**Comment by reefab** [comment]
I made a PR to update the package version in HA: 

https://github.com/home-assistant/home-assistant/pull/13942

**Comment by fabaff** [comment]
Thanks for the quick response.
