### ISSUE TITLE
Convert @asyncio.coroutine to async/await keywords

### ISSUE THREAD

**Issue by balloob** [reefab/foobot_async#5]
Python 3.5 (released 2015) introduced new `async` and `await` keywords. They replace the `@asyncio.coroutine` decorator and `yield from`. 

The `@asyncio.coroutine` decorator has been deprecated in Python 3.8 and will be removed in Python 3.10.

It would be great if this package could migrate to using `async` and `await` keywords.

```python
# Old
@asyncio.coroutine
def something():
    yield from asyncio.sleep(1)

# New
async def something():
    await asyncio.sleep(1)
```

**Comment by reefab** [comment]
Now that I've dropped support for Python 3.4, this is doable. I'll get to it.

**Comment by reefab** [comment]
Package version 1.0.0 uploaded.

I do not have a working foobot device anymore, but I'll keep maintaining this package for such housekeeping tasks.
